=== macvif/NITIJP/pieski.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="pieski">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="rasa" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nazwa" type="xs:string"/>
              <xs:element name="pochodzenie" type="xs:string"/>
              <xs:element name="wielkosc" type="xs:string"/>
              <xs:element name="charakter" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== macvif/NITIJP/pieski.xml
<?xml version="1.0" encoding="UTF-8"?>
<pieski xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="pieski.xsd">
  <rasa id="1">
    <nazwa>Owczarek niemiecki</nazwa>
    <pochodzenie>Niemcy</pochodzenie>
    <wielkosc>Duża</wielkosc>
    <charakter>
      Inteligentny, posłuszny
    </charakter>
  </rasa>
   <rasa id="2">
    <nazwa>Jamnik</nazwa>
    <pochodzenie>Polska</pochodzenie>
    <wielkosc>Mała</wielkosc>
    <charakter>
      Czujny, odważny
    </charakter>
  </rasa>
  <rasa id="3">
    <nazwa>Beagle</nazwa>
    <pochodzenie>Wielka Brytania</pochodzenie>
    <wielkosc>Średnia</wielkosc>
    <charakter>
      Przyjazny, energiczny
    </charakter>
  </rasa>
</pieski>
